urls:
  toxic_comments: https://drive.google.com/uc?id=1VuQ-U7TtggShMeuRSA_hzC8qGDl2LRkr

data_labels:
  - toxic
  - severe_toxic
  - obscene
  - threat
  - insult
  - identity_hate
  
transformer_model: bert-base-cased

max_token_count: 512